Fix build error for ref_picture
double check once again whether pic or decoded_frame might need to be
used here instead

error[E0609]: no field `handle` on type `&codec::h264::dpb::DpbEntry<V4l2StatelessDecoderHandle>`
  --> src/decoder/stateless/h264/v4l2.rs:83:44
   |
83 |             let ref_picture = match &entry.handle {
   |                                            ^^^^^^ unknown field
   |
   = note: available fields are: `pic`, `reference`, `decoded_frame`